from ast_nodes import RuleNode, AnyNode, IPNode, CIDRNode


def _convert_rule(rule: RuleNode, rule_num: int) -> str:
    """
    Convert a single RuleNode into one nftables rule line.

    nftables syntax:  [match ...] verdict comment "..."
    """
    parts = []

    src = rule.source
    if isinstance(src, (IPNode, CIDRNode)):
        parts.append(f"ip saddr {src.value}")

    dst = rule.destination
    if isinstance(dst, (IPNode, CIDRNode)):
        parts.append(f"ip daddr {dst.value}")

    proto = rule.protocol_str.lower()
    if proto in ("tcp", "udp"):
        parts.append(proto)
    elif proto == "icmp":
        parts.append("ip protocol icmp")

    if rule.port is not None:
        parts.append(f"dport {rule.port.number}")

    verdict = "accept" if rule.action_str == "ALLOW" else "drop"
    parts.append(verdict)

    parts.append(f'comment "FRL rule {rule_num}: {rule.action_str}"')

    return "        " + " ".join(parts)


def convert_to_nftables(rules) -> str:
    lines = [
        "#!/usr/sbin/nft -f",
        "# ============================================================",
        "# Generated by FRLc — Firewall Rule Language Compiler",
        "# Target: nftables (modern Linux netfilter)",
        "# ============================================================",
        "",
        "# Flush existing ruleset",
        "flush ruleset",
        "",
        "table inet frl_firewall {",
        "    chain input {",
        "        type filter hook input priority 0; policy drop;",
        "",
    ]

    for i, rule in enumerate(rules, start=1):
        lines.append(_convert_rule(rule, i))

    lines += [
        "",
        "    }",
        "}",
    ]

    return "\n".join(lines)


def convert_all_rules_nft(rules):
    return [_convert_rule(r, i).strip() for i, r in enumerate(rules, 1)]
